from declensions import Noun

# not finished
groups = {
    "generic": [
        Noun("m", "Mann", "Mannes", nom_pl="Männer", dat_pl="Männern"),
        Noun("f", "Frau", nom_pl="Frauen"),
        Noun("n", "Person", nom_pl="Personen", neopronouns=True),
    ],
    "111": [
        Noun("m", "Agrarökonom", status="Experte"),
        Noun("f", "Agrarökonomin", status="Experte"),
        Noun("m", "Bauer", status="Fachkraft"),
        Noun("f", "Bäuerin", status="Fachkraft"),
        Noun("m", "Erntehelfer", status="Helfer"),
        Noun("f", "Erntehelferin", status="Helfer"),
        Noun("m", "Landwirt", status="Spezialist"),
        Noun("f", "Landwirtin", status="Spezialist"),
    ],
    "112": [
        Noun("m", "Imker", status="Fachkraft"),
        Noun("f", "Imkerin", status="Fachkraft"),
        Noun("m", "Hirte", status="Fachkraft"),
        Noun("f", "Hirtin", status="Fachkraft"),
        Noun("m", "Viehtreiber", status="Helfer"),
        Noun("f", "Viehtreiberin", status="Helfer"),
        Noun("m", "Futterberater", status="Spezialist"),
        Noun("f", "Futterberaterin", status="Spezialist"),
    ],
    "113": [
        Noun("m", "Kutscher", status="Fachkraft"),
        Noun("f", "Kutscherin", status="Fachkraft"),
        Noun("m", "Hufschmied", status="Spezialist"),
        Noun("f", "Hufschmiedin", status="Spezialist"),
        Noun("m", "Pferdepfleger", status="Fachkraft"),
        Noun("f", "Pferdepflegerin", status="Fachkraft"),
    ],
    "114": [
        Noun("m", "Fischer", status="Fachkraft"),
        Noun("f", "Fischerin", status="Fachkraft"),
        Noun("m", "Fischzüchter", status="Fachkraft"),
        Noun("f", "Fischzüchterin", status="Fachkraft"),
        Noun("m", "Fischereitechniker", status="Spezialist"),
        Noun("f", "Fischereitechnikerin", status="Spezialist"),
        Noun("m", "Fischereiingenieur", status="Experte"),
        Noun("f", "Fischereiingenieurin", status="Experte"),
    ],
    "115": [
        Noun("m", "Falkner", status="Fachkraft"),
        Noun("f", "Falknerin", status="Fachkraft"),
        Noun("m", "Zoowärter", status="Fachkraft"),
        Noun("f", "Zoowärterin", status="Fachkraft"),
        Noun("m", "Hundetrainer", status="Fachkraft"),
        Noun("f", "Hundetrainerin", status="Fachkraft"),
        Noun("m", "Tierpfleger", status="Fachkraft"),
        Noun("f", "Tierpflegerin", status="Fachkraft"),
    ],
    "116": [
        Noun("m", "Önologe", status="Experte"),
        Noun("f", "Önologin", status="Experte"),
        Noun("m", "Winzer", status="Fachkraft"),
        Noun("f", "Winzerin", status="Fachkraft"),
        Noun("m", "Weinbautechniker", status="Spezialist"),
        Noun("f", "Weinbautechnikerin", status="Spezialist"),    
    ],
    "117": [
        Noun("m", "Forstwissenschaftler", status="Experte"),
        Noun("f", "Forstwissenschaftlerin", status="Experte"),
        Noun("m", "Jäger", status="Fachkraft"),
        Noun("f", "Jägerin", status="Fachkraft"),
        Noun("m", "Forstarbeiter", status="Helfer"),
        Noun("f", "Forstarbeiterin", status="Helfer"),
        Noun("m", "Förster", status="Spezialist"),
        Noun("f", "Försterin", status="Spezialist"),
    ],
    "121": [
        Noun("m", "Gartenarchitekt", status="Experte"),
        Noun("f", "Gartenarchitektin", status="Experte"),
        Noun("m", "Gemüsegärtner", status="Fachkraft"),
        Noun("f", "Gemüsegärtnerin", status="Fachkraft"),
        Noun("m", "Gartenarbeiter", status="Helfer"),
        Noun("f", "Gartenarbeiterin", status="Helfer"),
        Noun("m", "Saatzüchter", status="Spezialist"),
        Noun("f", "Saatzüchterin", status="Spezialist"),
    ],
    "122": [
        Noun("m", "Florist", status="Fachkraft"),
        Noun("f", "Floristin", status="Fachkraft"),
        Noun("m", "Floralgestalter", status="Spezialist"),
        Noun("f", "Floralgestalterin", status="Spezialist"),
    ],
    "811": [
        Noun("m", "Arzthelfer", status="Fachkraft"),
        Noun("f", "Arzthelferin", status="Fachkraft"),
        Noun("m", "Kastrierer", status="Spezialist"),
        Noun("f", "Kastriererin", status="Spezialist"),
    ],
    "812": [
        Noun("m", "Infektologe", status="Experte"),
        Noun("f", "Infektologin", status="Experte"), 
        Noun("m", "Pathologe", status="Experte"),
        Noun("f", "Pathologin", status="Experte"),
        Noun("m", "Radiologieassistent", status="Fachkraft"),
        Noun("f", "Radiologieassistentin", status="Fachkraft"),
        Noun("m", "Kardiotechniker", status="Spezialist"),
        Noun("f", "Kardiotechnikerin", status="Spezialist"),
        ],
    "813": [
        Noun("m", "Pflegeassistent", status="Helfer"),
        Noun("f", "Pflegeassistentin", status="Helfer"),
        Noun("f", "Hebamme", status="Spezialist", neopronouns=True),
        Noun("m", "Krankenpfleger", status="Fachkraft"),
        Noun("f", "Krankenpflegerin", status="Fachkraft"),
        Noun("m", "Notfallsanitäter", status="Fachkraft"),
        Noun("f", "Notfallsanitäterin", status="Fachkraft"),

    ],
    "814": [
        Noun("m", "Hausarzt", status="Experte"),
        Noun("f", "Hausärztin", status="Experte"),
        Noun("m", "Arzt", status="Experte"),
        Noun("f", "Ärztin", status="Experte"),
        Noun("m", "Facharzt", status="Experte"),
        Noun("f", "Fachärztin", status="Experte"),
        Noun("m", "Chirurg", status="Experte"),
        Noun("f", "Chirurgin", status="Experte"),
        ],
    "815": [
        Noun("m", "Tierarzt", status="Experte"),
        Noun("f", "Tierärztin", status="Experte"),
    ],
    "816": [
        Noun("m", "Psychotherapeut", status="Experte"),
        Noun("f", "Psychotherapeutin", status="Experte"),
        Noun("m", "Suchttherapeut", status="Experte"),
        Noun("f", "Suchttherapeutin", status="Experte"),
    ],
    "817": [
        Noun("m", "Physiotherapeut", status="Experte"),
        Noun("f", "Physiotherapeutin", status="Experte"),
        Noun("m", "Musiktherapeut", status="Spezialist"),
        Noun("f", "Musiktherapeutin", status="Spezialist"),
        Noun("m", "Masseur", status="Fachkraft"),
        Noun("f", "Masseurin", status="Fachkraft"),
    ],
    "818": [
        Noun("m", "Apotheker", status="Experte"),
        Noun("f", "Apothekerin", status="Experte"),
        Noun("m", "Pharmalaborant", status="Fachkraft"),
        Noun("f", "Pharmalaborantin", status="Fachkraft"),
        Noun("m", "Pharmaberater", status="Spezialist"),
        Noun("f", "Pharmaberaterin", status="Spezialist"),
    ],
    "821": [
        Noun("m", "Altenpfleger", status="Fachkraft"),
        Noun("f", "Altenpflegerin", status="Fachkraft"),
        Noun("m", "Pflegehelfer", status="Helfer"),
        Noun("f", "Pflegehelferin", status="Helfer"),
        Noun("m", "Fachaltenpfleger", status="Spezialist"),
        Noun("f", "Fachaltenpflegerin", status="Spezialist"),
    ],
    "822": [
        Noun("m", "Gesundheitswissenschaftler", status="Experte"),
        Noun("f", "Gesundheitswissenschaftlerin", status="Experte"),
        Noun("m", "Gesundheitscoach", neopronouns=True, status="Fachkraft"),
        Noun("m", "Ernährungsberater", status="Spezialist"),
        Noun("f", "Ernährungsberaterin", status="Spezialist"),
    ],
    "823": [
        Noun("m", "Friseur", status="Fachkraft"),
        Noun("f", "Friseurin", status="Fachkraft"),
        Noun("m", "Tätowierer", status="Fachkraft"),
        Noun("f", "Tätowiererin", status="Fachkraft"),
        Noun("m", "Shampooneur", status="Helfer"),
        Noun("f", "Shampooneurin", status="Helfer"),
        Noun("m", "Maskenbildner", status="Spezialist"),
        Noun("f", "Maskenbildnerin", status="Spezialist"),
        ],
    "824": [
        Noun("m", "Leichenbestatter", status="Fachkraft"),
        Noun("f", "Leichenbestatterin", status="Fachkraft"),
        Noun("m", "Totengräber", status="Helfer"),
        Noun("f", "Totengräberin", status="Helfer"),
        Noun("m", "Bestatter", status="Spezialist"),
        Noun("f", "Bestatterin", status="Spezialist"),
    ],
    "825": [
        Noun("m", "Optiker", status="Fachkraft"),
        Noun("f", "Optikerin", status="Fachkraft"),
        Noun("m", "Zahntechniker", status="Fachkraft"),
        Noun("f", "Zahntechnikerin", status="Fachkraft"),
        Noun("m", "Medizintechniker", status="Spezialist"),
        Noun("f", "Medizintechnikerin", status="Spezialist"),
    ],
    "831": [
        Noun("m", "Jugendberater", status="Experte"),
        Noun("f", "Jugendberaterin", status="Experte"),
        Noun("m", "Sozialarbeiter", status="Fachkraft"),
        Noun("f", "Sozialarbeiterin", status="Fachkraft"),
        Noun("m", "Sozialhelfer", status="Fachkraft"),
        Noun("f", "Sozialhelferin", status="Fachkraft"),
        Noun("m", "Schulbegleiter", status="Helfer"),
        Noun("f", "Schulbegleiterin", status="Helfer"),
        Noun("m", "Betreuer", status="Helfer"),
        Noun("f", "Betreuerin", status="Helfer"),
        Noun("m", "Erzieher", status="Spezialist"),
        Noun("f", "Erzieherin", status="Spezialist"),
        Noun("m", "Kindergärtner", status="Spezialist"),
        Noun("f", "Kindergärtnerin", status="Spezialist"),
    ],
    "832": [
        Noun("m", "Haushälter", status="Fachkraft"),
        Noun("f", "Haushälterin", status="Fachkraft"),
        Noun("m", "Haushaltsökonom", status="Spezialist"),        
        Noun("f", "Haushaltsökonomin", status="Spezialist"),
    ],
    "833": [
        Noun("m", "Priester", status="Experte"),
        Noun("f", "Priesterin", status="Experte"),
        Noun("m", "Pfarrer", status="Experte"),
        Noun("f", "Pfarrerin", status="Experte"),
        Noun("m", "Abt", status="Spezialist"),
        Noun("f", "Äbtissin", status="Spezialist"),
    ],
    "841": [
        Noun("m", "Lehrer", status="Experte"),
        Noun("f", "Lehrerin", status="Experte"),
        Noun("m", "Lernbetreuer", status="Spezialist"),
        Noun("f", "Lernbetreuerin", status="Spezialist"),
    ],
    "842": [
        Noun("m", "Berufsschullehrer", status="Experte"),
        Noun("f", "Berufsschullehrerin", status="Experte"),
        Noun("m", "Mentor", status="Spezialist"),
        Noun("f", "Mentorin", status="Spezialist"),
    ],
    "843": [
        Noun("m", "Dozent", status="Experte"),
        Noun("f", "Dozentin", status="Experte"),
        Noun("m", "Professor", status="Experte"),
        Noun("f", "Professorin", status="Experte"),    
    ],
    "844": [
        Noun("m", "Gitarrenlehrer", status="Experte"),
        Noun("f", "Gitarrenlehrerin", status="Experte"),
        Noun("m", "Musiklehrer", status="Fachkraft"),
        Noun("f", "Musiklehrerin", status="Fachkraft"),
        Noun("m", "Nachhilfelehrer", status="Spezialist"),
        Noun("f", "Nachhilfelehrerin", status="Spezialist"),
    ],
    "845": [
        Noun("m", "Sportwissenschaftler", status="Experte"),
        Noun("f", "Sportwissenschaftlerin", status="Experte"),
        Noun("m", "Fahrlehrer", status="Spezialist"),
        Noun("f", "Fahrlehrerin", status="Spezialist"),
        Noun("m", "Trainer", status="Spezialist"),
        Noun("f", "Trainerin", status="Spezialist"),
        ],
}  