from declensions import Noun

# not finished
groups = {
    "generic": [
        Noun("m", "Mann", "Mannes", nom_pl="Männer", dat_pl="Männern"),
        Noun("f", "Frau", nom_pl="Frauen"),
        Noun("n", "Person", nom_pl="Personen", neopronouns=True),
    ],
    "111": [
        Noun("m", "Agrarökonom", status="Experte"),
        Noun("f", "Agrarökonomin", status="Experte"),
        Noun("m", "Bauer", status="Fachkraft"),
        Noun("f", "Bäuerin", status="Fachkraft"),
        Noun("m", "Erntehelfer", status="Helfer"),
        Noun("f", "Erntehelferin", status="Helfer"),
        Noun("m", "Landwirt", status="Spezialist"),
        Noun("f", "Landwirtin", status="Spezialist"),
    ],
    "112": [
        Noun("m", "Imker", status="Fachkraft"),
        Noun("f", "Imkerin", status="Fachkraft"),
        Noun("m", "Hirte", status="Fachkraft"),
        Noun("f", "Hirtin", status="Fachkraft"),
        Noun("m", "Viehtreiber", status="Helfer"),
        Noun("f", "Viehtreiberin", status="Helfer"),
        Noun("m", "Futterberater", status="Spezialist"),
        Noun("f", "Futterberaterin", status="Spezialist"),
    ],
    "113": [
        Noun("m", "Kutscher", status="Fachkraft"),
        Noun("f", "Kutscherin", status="Fachkraft"),
        Noun("m", "Hufschmied", status="Spezialist"),
        Noun("f", "Hufschmiedin", status="Spezialist"),
        Noun("m", "Pferdepfleger", status="Fachkraft"),
        Noun("f", "Pferdepflegerin", status="Fachkraft"),
    ],
    "114": [
        Noun("m", "Fischer", status="Fachkraft"),
        Noun("f", "Fischerin", status="Fachkraft"),
        Noun("m", "Fischzüchter", status="Fachkraft"),
        Noun("f", "Fischzüchterin", status="Fachkraft"),
        Noun("m", "Fischereitechniker", status="Spezialist"),
        Noun("f", "Fischereitechnikerin", status="Spezialist"),
        Noun("m", "Fischereiingenieur", status="Experte"),
        Noun("f", "Fischereiingenieurin", status="Experte"),
    ],
    "115": [
        Noun("m", "Falkner", status="Fachkraft"),
        Noun("f", "Falknerin", status="Fachkraft"),
        Noun("m", "Zoowärter", status="Fachkraft"),
        Noun("f", "Zoowärterin", status="Fachkraft"),
        Noun("m", "Hundetrainer", status="Fachkraft"),
        Noun("f", "Hundetrainerin", status="Fachkraft"),
        Noun("m", "Tierpfleger", status="Fachkraft"),
        Noun("f", "Tierpflegerin", status="Fachkraft"),
    ],
    "116": [
        Noun("m", "Önologe", status="Experte"),
        Noun("f", "Önologin", status="Experte"),
        Noun("m", "Winzer", status="Fachkraft"),
        Noun("f", "Winzerin", status="Fachkraft"),
        Noun("m", "Weinbautechniker", status="Spezialist"),
        Noun("f", "Weinbautechnikerin", status="Spezialist"),    
    ],
    "117": [
        Noun("m", "Forstwissenschaftler", status="Experte"),
        Noun("f", "Forstwissenschaftlerin", status="Experte"),
        Noun("m", "Jäger", status="Fachkraft"),
        Noun("f", "Jägerin", status="Fachkraft"),
        Noun("m", "Forstarbeiter", status="Helfer"),
        Noun("f", "Forstarbeiterin", status="Helfer"),
        Noun("m", "Förster", status="Spezialist"),
        Noun("f", "Försterin", status="Spezialist"),
    ],
    "121": [
        Noun("m", "Gartenarchitekt", status="Experte"),
        Noun("f", "Gartenarchitektin", status="Experte"),
        Noun("m", "Gemüsegärtner", status="Fachkraft"),
        Noun("f", "Gemüsegärtnerin", status="Fachkraft"),
        Noun("m", "Gartenarbeiter", status="Helfer"),
        Noun("f", "Gartenarbeiterin", status="Helfer"),
        Noun("m", "Saatzüchter", status="Spezialist"),
        Noun("f", "Saatzüchterin", status="Spezialist"),
    ],
    "122": [
        Noun("m", "Florist", status="Fachkraft"),
        Noun("f", "Floristin", status="Fachkraft"),
        Noun("m", "Floralgestalter", status="Spezialist"),
        Noun("f", "Floralgestalterin", status="Spezialist"),
    ],
    "811": [
        Noun("m", "Arzthelfer", status="Fachkraft"),
        Noun("f", "Arzthelferin", status="Fachkraft"),
        Noun("m", "Kastrierer", status="Spezialist"),
        Noun("f", "Kastriererin", status="Spezialist"),
    ],
    "812": [
        Noun("m", "Infektologe", status="Experte"),
        Noun("f", "Infektologin", status="Experte"), 
        Noun("m", "Pathologe", status="Experte"),
        Noun("f", "Pathologin", status="Experte"),
        Noun("m", "Radiologieassistent", status="Fachkraft"),
        Noun("f", "Radiologieassistentin", status="Fachkraft"),
        Noun("m", "Kardiotechniker", status="Spezialist"),
        Noun("f", "Kardiotechnikerin", status="Spezialist"),
        ],
    "813": [
        Noun("m", "Pflegeassistent", status="Helfer"),
        Noun("f", "Pflegeassistentin", status="Helfer"),
        Noun("f", "Hebamme", status="Spezialist", neopronouns=True),
        Noun("m", "Krankenpfleger", status="Fachkraft"),
        Noun("f", "Krankenpflegerin", status="Fachkraft"),
        Noun("m", "Notfallsanitäter", status="Fachkraft"),
        Noun("f", "Notfallsanitäterin", status="Fachkraft"),

    ],
    "814": [
        Noun("m", "Hausarzt", status="Experte"),
        Noun("f", "Hausärztin", status="Experte"),
        Noun("m", "Arzt", status="Experte"),
        Noun("f", "Ärztin", status="Experte"),
        Noun("m", "Facharzt", status="Experte"),
        Noun("f", "Fachärztin", status="Experte"),
        Noun("m", "Chirurg", status="Experte"),
        Noun("f", "Chirurgin", status="Experte"),
        ],
    "815": [
        Noun("m", "Tierarzt", status="Experte"),
        Noun("f", "Tierärztin", status="Experte"),
    ],
    "816": [
        Noun("m", "Psychotherapeut", status="Experte"),
        Noun("f", "Psychotherapeutin", status="Experte"),
        Noun("m", "Suchttherapeut", status="Experte"),
        Noun("f", "Suchttherapeutin", status="Experte"),
    ],
    "817": [
        Noun("m", "Physiotherapeut", status="Experte"),
        Noun("f", "Physiotherapeutin", status="Experte"),
        Noun("m", "Musiktherapeut", status="Spezialist"),
        Noun("f", "Musiktherapeutin", status="Spezialist"),
        Noun("m", "Masseur", status="Fachkraft"),
        Noun("f", "Masseurin", status="Fachkraft"),
    ],
    "818": [
        Noun("m", "Apotheker", status="Experte"),
        Noun("f", "Apothekerin", status="Experte"),
        Noun("m", "Pharmalaborant", status="Fachkraft"),
        Noun("f", "Pharmalaborantin", status="Fachkraft"),
        Noun("m", "Pharmaberater", status="Spezialist"),
        Noun("f", "Pharmaberaterin", status="Spezialist"),
    ],
    "821": [
        Noun("m", "Altenpfleger", status="Fachkraft"),
        Noun("f", "Altenpflegerin", status="Fachkraft"),
        Noun("m", "Pflegehelfer", status="Helfer"),
        Noun("f", "Pflegehelferin", status="Helfer"),
        Noun("m", "Fachaltenpfleger", status="Spezialist"),
        Noun("f", "Fachaltenpflegerin", status="Spezialist"),
    ],
    "822": [
        Noun("m", "Gesundheitswissenschaftler", status="Experte"),
        Noun("f", "Gesundheitswissenschaftlerin", status="Experte"),
        Noun("m", "Gesundheitscoach", neopronouns=True, status="Fachkraft"),
        Noun("m", "Ernährungsberater", status="Spezialist"),
        Noun("f", "Ernährungsberaterin", status="Spezialist"),
    ],
    "823": [
        Noun("m", "Friseur", status="Fachkraft"),
        Noun("f", "Friseurin", status="Fachkraft"),
        Noun("m", "Tätowierer", status="Fachkraft"),
        Noun("f", "Tätowiererin", status="Fachkraft"),
        Noun("m", "Shampooneur", status="Helfer"),
        Noun("f", "Shampooneurin", status="Helfer"),
        Noun("m", "Maskenbildner", status="Spezialist"),
        Noun("f", "Maskenbildnerin", status="Spezialist"),
        ],
    "824": [
        Noun("m", "Leichenbestatter", status="Fachkraft"),
        Noun("f", "Leichenbestatterin", status="Fachkraft"),
        Noun("m", "Totengräber", status="Helfer"),
        Noun("f", "Totengräberin", status="Helfer"),
        Noun("m", "Bestatter", status="Spezialist"),
        Noun("f", "Bestatterin", status="Spezialist"),
    ],
    "825": [
        Noun("m", "Optiker", status="Fachkraft"),
        Noun("f", "Optikerin", status="Fachkraft"),
        Noun("m", "Zahntechniker", status="Fachkraft"),
        Noun("f", "Zahntechnikerin", status="Fachkraft"),
        Noun("m", "Medizintechniker", status="Spezialist"),
        Noun("f", "Medizintechnikerin", status="Spezialist"),
    ],
    "831": [
        Noun("m", "Jugendberater", status="Experte"),
        Noun("f", "Jugendberaterin", status="Experte"),
        Noun("m", "Sozialarbeiter", status="Fachkraft"),
        Noun("f", "Sozialarbeiterin", status="Fachkraft"),
        Noun("m", "Sozialhelfer", status="Fachkraft"),
        Noun("f", "Sozialhelferin", status="Fachkraft"),
        Noun("m", "Schulbegleiter", status="Helfer"),
        Noun("f", "Schulbegleiterin", status="Helfer"),
        Noun("m", "Betreuer", status="Helfer"),
        Noun("f", "Betreuerin", status="Helfer"),
        Noun("m", "Erzieher", status="Spezialist"),
        Noun("f", "Erzieherin", status="Spezialist"),
        Noun("m", "Kindergärtner", status="Spezialist"),
        Noun("f", "Kindergärtnerin", status="Spezialist"),
    ],
    "832": [
        Noun("m", "Haushälter", status="Fachkraft"),
        Noun("f", "Haushälterin", status="Fachkraft"),
        Noun("m", "Haushaltsökonom", status="Spezialist"),        
        Noun("f", "Haushaltsökonomin", status="Spezialist"),
    ],
    "833": [
        Noun("m", "Priester", status="Experte"),
        Noun("f", "Priesterin", status="Experte"),
        Noun("m", "Pfarrer", status="Experte"),
        Noun("f", "Pfarrerin", status="Experte"),
        Noun("m", "Abt", status="Spezialist"),
        Noun("f", "Äbtissin", status="Spezialist"),
    ],
    "841": [
        Noun("m", "Lehrer", status="Experte"),
        Noun("f", "Lehrerin", status="Experte"),
        Noun("m", "Lernbetreuer", status="Spezialist"),
        Noun("f", "Lernbetreuerin", status="Spezialist"),
    ],
    "842": [
        Noun("m", "Berufsschullehrer", status="Experte"),
        Noun("f", "Berufsschullehrerin", status="Experte"),
        Noun("m", "Mentor", status="Spezialist"),
        Noun("f", "Mentorin", status="Spezialist"),
    ],
    "843": [
        Noun("m", "Dozent", status="Experte"),
        Noun("f", "Dozentin", status="Experte"),
        Noun("m", "Professor", status="Experte"),
        Noun("f", "Professorin", status="Experte"),    
    ],
    "844": [
        Noun("m", "Gitarrenlehrer", status="Experte"),
        Noun("f", "Gitarrenlehrerin", status="Experte"),
        Noun("m", "Musiklehrer", status="Fachkraft"),
        Noun("f", "Musiklehrerin", status="Fachkraft"),
        Noun("m", "Nachhilfelehrer", status="Spezialist"),
        Noun("f", "Nachhilfelehrerin", status="Spezialist"),
    ],
    "845": [
        Noun("m", "Sportwissenschaftler", status="Experte"),
        Noun("f", "Sportwissenschaftlerin", status="Experte"),
        Noun("m", "Fahrlehrer", status="Spezialist"),
        Noun("f", "Fahrlehrerin", status="Spezialist"),
        Noun("m", "Trainer", status="Spezialist"),
        Noun("f", "Trainerin", status="Spezialist"),
        ],
        "311": [
        Noun("m", "Architekt", "Architekten", nom_pl="Architekten", dat_pl="Architekten", status="Experte"),
        Noun("f", "Architektin", nom_pl="Architektinnen", status="Experte"),
        Noun("m", "Raumplaner", "Raumplaners", nom_pl="Raumplaner", status="Experte"),
        Noun("f", "Raumplanerin", nom_pl="Raumplanerinnen", status="Experte"),
        Noun("m", "Altbausanierer", "Altbausanierers", nom_pl="Altbausanierer", status="Fachkraft"),
        Noun("f", "Altbausaniererin", nom_pl="Altbausaniererinnen", status="Fachkraft"),
        Noun("m", "Baustellenprüfer", "Baustellenprüfers", nom_pl="Baustellenprüfer", status="Spezialist"),
        Noun("f", "Baustellenprüferin", nom_pl="Baustellenprüferinnen", status="Spezialist"),
    ],
    "312": [
        Noun("m", "Geodät", "Geodäten", nom_pl="Geodäten", dat_pl="Geodäten", status="Experte"),
        Noun("f", "Geodätin", nom_pl="Geodätinnen", status="Experte"),
        Noun("m", "Landkartenzeichner", "Landkartenzeichners", nom_pl="Landkartenzeichner", status="Fachkraft"),
        Noun("f", "Landkartenzeichnerin", nom_pl="Landkartenzeichnerinnen", status="Fachkraft"),
        Noun("m", "Luftbildtechniker", "Luftbildtechnikers", nom_pl="Luftbildtechniker", status="Spezialist"),
        Noun("f", "Luftbildtechnikerin", nom_pl="Luftbildtechnikerinnen", status="Spezialist"),
    ],
    "321": [
        Noun("m", "Bauingenieur", "Bauingenieurs", nom_pl="Bauingenieure", dat_pl="Bauingenieuren", status="Experte"),
        Noun("f", "Bauingenieurin", nom_pl="Bauingenieurinnen", status="Experte"),
        Noun("m", "Maurer", "Maurers", nom_pl="Maurer", status="Fachkraft"),
        Noun("f", "Maurerin", nom_pl="Maurerinnen", status="Fachkraft"),
        Noun("m", "Bauwerker", "Bauwerkers", nom_pl="Bauwerker", status="Helfer"),
        Noun("f", "Bauwerkerin", nom_pl="Bauwerkerinnen", status="Helfer"),
        Noun("m", "Betonbautechniker", "Betonbautechnikers", nom_pl="Betonbautechniker", status="Spezialist"),
        Noun("f", "Betonbautechnikerin", nom_pl="Betonbautechnikerinnen", status="Spezialist"),
    ],
    "322": [
        Noun("m", "Straßenbauingenieur", "Straßenbauingenieurs", nom_pl="Straßenbauingenieure", dat_pl="Straßenbauingenieuren", status="Experte"),
        Noun("f", "Straßenbauingenieurin", nom_pl="Straßenbauingenieurinnen", status="Experte"),
        Noun("m", "Kanalbauer", "Kanalbauers", nom_pl="Kanalbauer", status="Fachkraft"),
        Noun("f", "Kanalbauerin", nom_pl="Kanalbauerinnen", status="Fachkraft"),
        Noun("m", "Straßearbeiter", "Straßenarbeiters", nom_pl="Straßenarbeiter", status="Helfer"),
        Noun("f", "Straßearbeiterin", nom_pl="Straßenarbeiterinnen", status="Helfer"),
        Noun("m", "Brunnenbautechniker", "Brunnenbautetechnikers", nom_pl="Brunnenbautetechniker", status="Spezialist"),
        Noun("f", "Brunnenbautechnikerin", nom_pl="Brunnenbautechnikerinnen", status="Spezialist"),
    ],
    "331": [
        Noun("m", "Bodenverleger", "Bodenverlegers", nom_pl="Bodenverleger", status="Fachkraft"),
        Noun("f", "Bodenverlegerin", nom_pl="Bodenverlegerinnen", status="Fachkraft"),
        Noun("m", "Fliesenlegerhelfer", "Fliesenlegerhelfers", nom_pl="Fliesenlegerhelfer", status="Helfer"),
        Noun("f", "Fliesenlegerhelferin", nom_pl="Fliesenlegerhelferinnen", status="Helfer"),
        Noun("m", "Parkettrestaurator", "Parkettrestaurators", nom_pl="Parkettrestauratoren", status="Spezialist"),
        Noun("f", "Parkettrestauratorin", nom_pl="Parkettrestauratorinnen", status="Spezialist"),
    ],
    "332": [
        Noun("m", "Maler", "Malers", nom_pl="Maler", status="Fachkraft"),
        Noun("f", "Malerin", nom_pl="Malern", status="Fachkraft"),
        Noun("m", "Malerhelfer", "Malerhelfers", nom_pl="Malerhelfer", status="Helfer"),
        Noun("f", "Malerhelferin", nom_pl="Malerhelferinnen", status="Helfer"),
        Noun("m", "Stuckateur", "Stuckateurs", nom_pl="Stuckateure", status="Spezialist"),
        Noun("f", "Stuckateurin", nom_pl="Stuckateurinnen", status="Spezialist"),
    ],
    "333": [
        Noun("m", "Autoglaser", "Autoglasers", nom_pl="Autoglaser", status="Fachkraft"),
        Noun("f", "Autoglaserin", nom_pl="Autoglaserinnen", status="Fachkraft"),
        Noun("m", "Zimmerer", "Zimmerers", nom_pl="Zimmerer", status="Fachkraft"),
        Noun("f", "Zimmerin", nom_pl="Zimmerinnen", status="Fachkraft"),
        Noun("m", "Zimmererhelfer", "Zimmererhelfers", nom_pl="Zimmererhelfer", status="Helfer"),
        Noun("f", "Zimmererhelferin", nom_pl="Zimmererhelferinnen", status="Helfer"),
        Noun("m", "Restaurator", "Restaurators", nom_pl="Restauratoren", status="Spezialist"),
        Noun("f", "Restauratorin", nom_pl="Restauratorinnen", status="Spezialist"),
    ],
    "341": [
        Noun("m", "Hausmeister", "Hausmeisters", nom_pl="Hausmeister", status="Fachkraft"),
        Noun("f", "Hausmeisterin", nom_pl="Hausmeisterinnen", status="Fachkraft"),
        Noun("m", "Elektrotechniker", "Elektrotechnikers", nom_pl="Elektrotechniker", status="Spezialist"),
        Noun("f", "Elektrotechnikerin", nom_pl="Elektrotechnikerinnen", status="Spezialist"),
        ],
    "342": [
        Noun("m", "Klimaingenieur", "Klimaingenieurs", nom_pl="Klimaingenieure", dat_pl="Klimaingenieuren", status="Experte"),
        Noun("f", "Klimaingenieurin", nom_pl="Klimaingenieurinnen", status="Experte"),
        Noun("m", "Klempner", "Klempners", nom_pl="Klempner", status="Fachkraft"),
        Noun("f", "Klempnerin", nom_pl="Klempnerinnen", status="Fachkraft"),
        Noun("m", "Kesselblechtreiber", "Kesselblechtreibers", nom_pl="Kesselblechtreiber", status="Helfer"),
        Noun("f", "Kesselblechtreiberin", nom_pl="Kesselblechtreiberinnen", status="Helfer"),
        Noun("m", "Wärmetechniker", "Wärmetechnikers", nom_pl="Wärmetechniker", status="Spezialist"),
        Noun("f", "Wärmetechnikerin", nom_pl="Wärmetechnikerinnen", status="Spezialist"),
    ],
    "343": [
        Noun("m", "Sanitäringenieur", "Sanitäringenieurs", nom_pl="Sanitäringenieure", dat_pl="Sanitäringenieuren", status="Experte"),
        Noun("f", "Sanitäringenieurin", nom_pl="Sanitäringenieurinnen", status="Experte"),
        Noun("m", "Recycler", "Recyclers", nom_pl="Recycler", status="Fachkraft"),
        Noun("f", "Recyclerin", nom_pl="Recyclerinnen", status="Fachkraft"),
        Noun("m", "Müllmann", "Müllmanns", nom_pl="Müllmänner", status="Helfer"),
        Noun("f", "Müllfrau", nom_pl="Müllfrauen", status="Helfer"),
        Noun("m", "Abwasserberater", "Abwasserberaters", nom_pl="Abwasserberater", status="Spezialist"),
        Noun("f", "Abwasserberaterin", nom_pl="Abwasserberaterinnen", status="Spezialist"),
    ],
    "911": [
        Noun("m", "Literaturwissenschaftler", "Literaturwissenschaftlers", nom_pl="Literaturwissenschaftler", status="Experte"),
        Noun("f", "Literaturwissenschaftlerin", nom_pl="Literaturwissenschaftlerinnen", status="Experte"),
        Noun("m", "Linguist", "Linguisten", nom_pl="Linguisten", dat_pl="Linguisten", status="Experte"),
        Noun("f", "Linguistin", nom_pl="Linguistinnen", status="Experte"),
    ],
    "912": [
        Noun("m", "Archäologe", "Archäologen", nom_pl="Archäologen", dat_pl="Archäologen", status="Experte"),
        Noun("f", "Archäologin", nom_pl="Archäologinnen", status="Experte"),
        Noun("m", "Philosoph", "Philosophen", nom_pl="Philosophen", dat_pl="Philosophen", status="Experte"),
        Noun("f", "Philosophin", nom_pl="Philosophinnen", status="Experte"),
        Noun("m", "Historiker", "Historikers", nom_pl="Historiker", status="Experte"),
        Noun("f", "Historikerin", nom_pl="Historikerinnen", status="Experte"),
        Noun("m", "Grabungstechniker", "Grabungstechnikers", nom_pl="Grabungstechniker", status="Spezialist"),
        Noun("f", "Grabungstechnikerin", nom_pl="Grabungstechnikerinnen", status="Spezialist"),
    ],
    "913": [
        Noun("m", "Marktforscher", "Marktforschers", nom_pl="Marktforscher", status="Experte"),
        Noun("f", "Marktforscherin", nom_pl="Marktforscherinnen", status="Experte"),
        Noun("m", "Soziologe", "Soziologen", nom_pl="Soziologen", dat_pl="Soziologen", status="Experte"),
        Noun("f", "Soziologin", nom_pl="Soziologinnen", status="Experte"),
        Noun("m", "Interviewer", "Interviewers", nom_pl="Interviewer", status="Helfer"),
        Noun("f", "Interviewerin", nom_pl="Interviewerinnen", status="Helfer"),
        Noun("m", "Tester", "Testers", nom_pl="Tester", status="Spezialist"),
        Noun("f", "Testerin", nom_pl="Testerinnen", status="Spezialist"),
    ],
    "914": [
        Noun("m", "Ökonom", "Ökonomen", nom_pl="Ökonomen", dat_pl="Ökonomen", status="Experte"),
        Noun("f", "Ökonomin", nom_pl="Ökonominnen",status="Experte"),
    ],
    "921": [
        Noun("m", "Werbemanager", "Werbemanagers", nom_pl="Werbemanager", status="Experte"),
        Noun("f", "Werbemanagerin", nom_pl="Werbemanagerinnen", status="Experte"),
        Noun("m", "Callcenteragent", "Callcenteragents", nom_pl="Callcenteragents", status="Fachkraft"),
        Noun("f", "Callcenteragentin", nom_pl="Callcenteragentinnen", status="Fachkraft"),
        Noun("m", "Werbetexter", "Werbetexters", nom_pl="Werbetexter", status="Spezialist"),
        Noun("f", "Werbetexterin", nom_pl="Werbetexterinnen", status="Spezialist"),
    ],
    "922": [
        Noun("m", "Pressesprecher", "Pressesprechers", nom_pl="Pressesprecher", status="Experte"),
        Noun("f", "Pressesprecherin", nom_pl="Pressesprecherinnen", status="Experte"),
        Noun("m", "Lobbyist", "Lobbyisten", nom_pl="Lobbyisten", dat_pl="Lobbyisten", status="Spezialist"),
        Noun("f", "Lobbyistin", nom_pl="Lobbyistinnen", status="Spezialist"),
    ],
    "923": [
        Noun("m", "Literaturagent", "Literaturagents", nom_pl="Literaturagents", status="Experte"),
        Noun("f", "Literaturagentin", nom_pl="Literaturagentinnen", status="Experte"),
        Noun("m", "Buchhändler", "Buchhändlers", nom_pl="Buchhändler", status="Fachkraft"),
        Noun("f", "Buchhändlerin", nom_pl="Buchhändlerinnen", status="Fachkraft"),
        Noun("m", "Verlagsvertreter", "Verlagsvertreters", nom_pl="Verlagsvertreter", status="Spezialist"),
        Noun("f", "Verlagsvertreterin", nom_pl="Verlagsvertreterinnen", status="Spezialist"),
    ],
    "924": [
        Noun("m", "Reporter", "Reporters", nom_pl="Reporter", status="Experte"),
        Noun("f", "Reporterin", nom_pl="Reporterinnen", status="Experte"),
        Noun("m", "Dichter", "Dichters", nom_pl="Dichter", status="Experte"),
        Noun("f", "Dichterin", nom_pl="Dichterinnen", status="Experte"),
        Noun("m", "Journalist", "Journalisten", nom_pl="Journalisten", dat_pl="Journalisten", status="Experte"),
        Noun("f", "Journalistin", nom_pl="Journalistinnen", status="Experte"),
        Noun("m", "Redaktionsassistent", "Redaktionsassistenten", nom_pl="Redaktionsassistenten", status="Fachkraft"),
        Noun("f", "Redaktionsassistentin", nom_pl="Redaktionsassistentinnen", status="Fachkraft"),
        Noun("m", "Redakteur", "Redakteurs", nom_pl="Redakteure", status="Spezialist"),
        Noun("f", "Redakteurin", nom_pl="Redakteurinnen", status="Spezialist"),
    ],
    "931": [
        Noun("m", "Möbeldesigner", "Möbeldesigners", nom_pl="Möbeldesigner", status="Experte"),
        Noun("f", "Möbeldesignerin", nom_pl="Möbeldesignerinnen", status="Experte"),
        Noun("m", "Möbelgestalter", "Möbelgestalters", nom_pl="Möbelgestalter", status="Spezialist"),
        Noun("f", "Möbelgestalterin", nom_pl="Möbelgestalterinnen", status="Spezialist"),
    ],
    "932": [
        Noun("m","Innenarchitekt", "Innenarchitekten", nom_pl="Innenarchitekten", dat_pl="Innenarchitekten", status="Experte"),
        Noun("f", "Innenarchitektin", nom_pl="Innenarchitektinnen", status="Experte"),
        Noun("m", "Innenausstatter", "Innenausstatters", nom_pl="Innenausstatter", status="Fachkraft"),
        Noun("f", "Innenausstatterin", nom_pl="Innenausstatterinnen", status="Fachkraft"),
        Noun("m", "Dekorationsberater", "Dekorationsberaters", nom_pl="Dekorationsberater", status="Spezialist"),
        Noun("f", "Dekorationsberaterin", nom_pl="Dekorationsberaterinnen", status="Spezialist"),
    ],
    "933": [
        Noun("m", "Restaurator", "Restaurators", nom_pl="Restauratoren", status="Experte"),
        Noun("f", "Restauratorin", nom_pl="Restauratorinnen", status="Experte"),
        Noun("m", "Bildhauer", "Bildhauers", nom_pl="Bildhauer", status="Fachkraft"),
        Noun("f", "Bildhauerin", nom_pl="Bildhauerinnen", status="Fachkraft"),
        Noun("m", "Karikaturist", "Karikaturisten", nom_pl="Karikaturisten", dat_pl="Karikaturisten", status="Spezialist"),
        Noun("f", "Karikaturistin", nom_pl="Karikaturistinnen", status="Spezialist"),
        Noun("m", "Kunstmaler", "Kunstmalers", nom_pl="Kunstmaler", status="Spezialist"),
        Noun("f", "Kunstmalerin", nom_pl="Kunstmalerinnen", status="Spezialist"),
    ],
    "934": [
        Noun("m", "Töpfer", "Töpfers", nom_pl="Töpfer", status="Fachkraft"),
        Noun("f", "Töpferin", nom_pl="Töpferinnen", status="Fachkraft"),
        Noun("m", "Keramikdesigner", "Keramikdesigners", nom_pl="Keramikdesigner", status="Spezialist"),
        Noun("f", "Keramikdesignerin", nom_pl="Keramikdesignerinnen", status="Spezialist"),
    ],
    "935": [
        Noun("m", "Schmuckdesigner", "Schmuckdesigners", nom_pl="Schmuckdesigner", status="Experte"),
        Noun("f", "Schmuckdesignerin", nom_pl="Schmuckdesignerinnen", status="Experte"),
        Noun("m", "Juwelier", "Juweliers", nom_pl="Juweliere", status="Fachkraft"),
        Noun("f", "Juwelierin", nom_pl="Juwelierinnen", status="Fachkraft"),
        Noun("m", "Goldschmied", "Goldschmieds", nom_pl="Goldschmiede", status="Spezialist"),
        Noun("f", "Goldschmiedin", nom_pl="Goldschmiedinnen", status="Spezialist"),
    ],
    "936": [
        Noun("m", "Musikinstrumentenbauer", "Musikinstrumentenbauers", nom_pl="Musikinstrumentenbauer", status="Experte"),
        Noun("f", "Musikinstrumentenbauerin", nom_pl="Musikinstrumentenbauerinnen", status="Experte"),
        Noun("m", "Geigenbauer", "Geigenbauers", nom_pl="Geigenbauer", status="Fachkraft"),
        Noun("f", "Geigenbauerin", nom_pl="Geigenbauerinnen", status="Fachkraft"),
        Noun("m", "Holzblasinstrumentenbauer", "Holzblasinstrumentenbauers", nom_pl="Holzblasinstrumentenbauer", status="Spezialist"),
        Noun("f", "Holzblasinstrumentenbauerin", nom_pl="Holzblasinstrumentenbauerinnen", status="Spezialist"),
    ],
    "941": [
        Noun("m", "Sänger", "Sängers", nom_pl="Sänger", status="Experte"),
        Noun("f", "Sängerin", nom_pl="Sängerinnen", status="Experte"),
        Noun("m", "Klaviespieler", "Klaviespielers", nom_pl="Klaviespieler", status="Experte"),
        Noun("f", "Klaviespielerin", nom_pl="Klaviespielerinnen", status="Experte"),
        Noun("m", "Sounddesigner", "Sounddesigners", nom_pl="Sounddesigner", status="Spezialist"),
        Noun("f", "Sounddesignerin", nom_pl="Sounddesignerinnen", status="Spezialist"),
    ],
    "942": [
        Noun("m", "Schauspieler", "Schauspielers", nom_pl="Schauspieler", status="Experte"),
        Noun("f", "Schauspielerin", nom_pl="Schauspielerinnen", status="Experte"),
        Noun("m", "Prostituierter", "Prostituierten", nom_pl="Prostituierten", status="Fachkraft"),
        Noun("f", "Prostituierte", nom_pl="Prostituierten", status="Fachkraft"),
        Noun("m", "Akrobat", "Akrobaten", nom_pl="Akrobaten", dat_pl="Akrobaten", status="Spezialist"),
        Noun("f", "Akrobatin", nom_pl="Akrobatinnen", status="Spezialist"),
        Noun("n", "Model", "Models", nom_pl="Models", status="Fachkraft", neopronouns=True),
    ],
    "943": [
        Noun("m", "Radiomoderator", "Radiomoderators", nom_pl="Radiomoderatoren", status="Experte"),
        Noun("f", "Radiomoderatorin", nom_pl="Radiomoderatorinnen", status="Experte"),
        Noun("m", "Hellseher", "Hellsehers", nom_pl="Hellseher", status="Fachkraft"),
        Noun("f", "Hellseherin", nom_pl="Hellseherinnen", status="Fachkraft"),
        Noun("m", "Wahrsager", "Wahrsagers", nom_pl="Wahrsager", status="Fachkraft"),
        Noun("f", "Wahrsagerin", nom_pl="Wahrsagerinnen", status="Fachkraft"),
        Noun("m", "Clown", "Clowns", nom_pl="Clowns", status="Spezialist"),
        Noun("f", "Clownin", nom_pl="Clowninnen", status="Spezialist"),
    ],
    "944": [
        Noun("m", "Producer", "Producers", nom_pl="Producers", status="Experte"),
        Noun("f", "Producerin", nom_pl="Producerinnen", status="Experte"),
        Noun("m", "Souffleur", "Souffleurs", nom_pl="Souffleurs", status="Fachkraft"),
        Noun("f", "Souffleuse", nom_pl="Souffleusen", status="Fachkraft"),
        Noun("m", "Regieassistent", "Regieassistenten", nom_pl="Regieassistenten", status="Spezialist"),
        Noun("f", "Regieassistentin", nom_pl="Regieassistentinnen", status="Spezialist"),
    ],
    "945": [
        Noun("m", "Tonmeister", "Tonmeisters", nom_pl="Tonmeister", status="Experte"),
        Noun("f", "Tonmeisterin", nom_pl="Tonmeisterinnen", status="Experte"),
        Noun("m", "Pyrotechniker", "Pyrotechnikers", nom_pl="Pyrotechniker", status="Fachkraft"),
        Noun("f", "Pyrotechnikerin", nom_pl="Pyrotechnikerinnen", status="Fachkraft"),
        Noun("m", "Kameramann", "Kameramanns", nom_pl="Kameramänner", status="Spezialist"),
        Noun("f", "Kamerafrau", nom_pl="Kamerafrauen", status="Spezialist"),
    ],
    "946": [
        Noun("m", "Kostümbildner", "Kostümbildners", nom_pl="Kostümbildner", status="Experte"),
        Noun("f", "Kostümbildnerin", nom_pl="Kostümbildnerinnen", status="Experte"),
        Noun("m", "Ankleider", "Ankleiders", nom_pl="Ankleider", status="Fachkraft"),
        Noun("f", "Ankleiderin", nom_pl="Ankleiderinnen", status="Fachkraft"),
        Noun("m", "Requisiteur", "Requisiteurs", nom_pl="Requisiteure", status="Spezialist"),
        Noun("f", "Requisiteurin", nom_pl="Requisiteurinnen", status="Spezialist"),
    ],
    "947": [
        Noun("m", "Kurator", "Kurators", nom_pl="Kuratoren", status="Experte"),
        Noun("f", "Kuratorin", nom_pl="Kuratorinnen", status="Experte"),
        Noun("m", "Museumstechniker", "Museumstechnikers", nom_pl="Museumstechniker", status="Spezialist"),
        Noun("f", "Museumstechnikerin", nom_pl="Museumstechnikerinnen", status="Spezialist"),
    ],
}  