from declensions import Name

names = [
    # Names
    # Name("Toni Kroos", "m"),
    # Name("Mesut Özil", "m"),
    # Name("Younes Zarou", "m"),
    # Name("Bastian Schweinsteiger", "m"),
    # Name("Marc ter Stegen", "m"),
    # Name("Thomas Müller", "m"),
    # Name("Manuel Neuer", "m"),
    # Name("Jerome Boateng", "m"),
    # Name("Mario Götze", "m"),
    # Name("Leroy Sané", "m"),
    # Name("Pamela ReiFEMININE", "FEMININE"),
    # Name("Lena Mantler", "FEMININE"),
    # Name("Pia Wurtzbach", "FEMININE"),
    # Name("Heidi Klum", "FEMININE"),
    # Name("Bianca Heinicke", "FEMININE"),
    # Name("Dagmar Kazakov", "FEMININE"),
    # Name("SteFEMININEanie Giesinger", "FEMININE"),
    # Name("Leonie Hanne", "FEMININE"),
    # Name("Caro Daur", "FEMININE"),
    # Name("Anna Maria Damm", "FEMININE"),
    # Name("Kim de l’Horizon", "d"),
    # Name("Nemo", "d"),
    # Name("FEMININEelix Jaehn", "d"),
    # Name("Maja T.", "d"),
    # Name("Sasha Marianna Salzmann", "d"),
    # Name("Judith Butler", "d"),
    # Name("Demi Lovato", "d"),
    # Name("Sam Smith", "d"),
    # Name("Bambie Thug", "d"),
    # Name("Blu del Barrio", "d"),
    # "Neutral" names
    Name("Janne", "NEUTRAL"),
    Name("Bente", "NEUTRAL"),
    Name("Nicola", "NEUTRAL"),
    Name("Alexis", "NEUTRAL"),
    Name("Kayra", "NEUTRAL"),
    Name("Lou", "NEUTRAL"),
    Name("Sascha", "NEUTRAL"),
    Name("Emilia", "FEMININE"),
    Name("Sophia", "FEMININE"),
    Name("Emma", "FEMININE"),
    Name("Hannah", "FEMININE"),
    Name("Mia", "FEMININE"),
    Name("Lina", "FEMININE"),
    Name("Noah", "MASCULINE"),
    Name("Matteo", "MASCULINE"),
    Name("Leon", "MASCULINE"),
    Name("Elias", "MASCULINE"),
    Name("Luca", "MASCULINE"),
    Name("Theo", "MASCULINE"),
]
