from declensions import Name

names = [
    # Names
    # Name("Toni Kroos", "m"),
    # Name("Mesut Özil", "m"),
    # Name("Younes Zarou", "m"),
    # Name("Bastian Schweinsteiger", "m"),
    # Name("Marc ter Stegen", "m"),
    # Name("Thomas Müller", "m"),
    # Name("Manuel Neuer", "m"),
    # Name("Jerome Boateng", "m"),
    # Name("Mario Götze", "m"),
    # Name("Leroy Sané", "m"),
    # Name("Pamela Reif", "f"),
    # Name("Lena Mantler", "f"),
    # Name("Pia Wurtzbach", "f"),
    # Name("Heidi Klum", "f"),
    # Name("Bianca Heinicke", "f"),
    # Name("Dagmar Kazakov", "f"),
    # Name("Stefanie Giesinger", "f"),
    # Name("Leonie Hanne", "f"),
    # Name("Caro Daur", "f"),
    # Name("Anna Maria Damm", "f"),
    # Name("Kim de l’Horizon", "d"),
    # Name("Nemo", "d"),
    # Name("Felix Jaehn", "d"),
    # Name("Maja T.", "d"),
    # Name("Sasha Marianna Salzmann", "d"),
    # Name("Judith Butler", "d"),
    # Name("Demi Lovato", "d"),
    # Name("Sam Smith", "d"),
    # Name("Bambie Thug", "d"),
    # Name("Blu del Barrio", "d"),
    # Neutral names
    Name("Janne", "n"),
    Name("Bente", "n"),
    Name("Nicola", "n"),
    Name("Alexis", "n"),
    Name("Kayra", "n"),
    Name("Lou", "n"),
    Name("Sascha", "n"),
    Name("Emilia", "f"),
    Name("Sophia", "f"),
    Name("Emma", "f"),
    Name("Hannah", "f"),
    Name("Mia", "f"),
    Name("Lina", "f"),
    Name("Noah", "m"),
    Name("Matteo", "m"),
    Name("Leon", "m"),
    Name("Elias", "m"),
    Name("Luca", "m"),
    Name("Theo", "m"),
]
